openapi: 3.0.1
info:
  title: Заказ облачного пространства
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
paths:
  /clouds:
    get:
      summary: Метод получения списка облачных ресурсов
      tags: 
        - Clouds
      operationId: getAllClouds
      responses:
        "200":
          description: Успешный ответ со спиcком облачных ресурсов
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: другие ответы, кроме успешного
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод создания заказа на пространство в облаке
      tags: 
        - Clouds
      operationId: createCloud
      requestBody:
        required: true
        content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Cloud" 
      responses:
        "200":
          description: Успешный ответ покупки пространства в облаке
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: другие ответы, кроме успешного
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
  /clouds/{idCloud}:
    get:
      summary: Метод получения заказа по id
      tags:
        - Clouds
      operationId: getCloudId
      parameters:
        - name: idCloud
          in: path
          required: true
          description: id заказа пространства в облаке
          schema:
            type: string
      responses:
        "200":
          description: Успешный ответ получения заказа по id
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: другие ответы, кроме успешного
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"     
    delete:
      summary: Удаление заказа пространства в облаке по id заказа
      tags:
        - Clouds
      operationId: deleteCloudById
      parameters:
        - name: idCloud
          in: path
          required: true
          description: id заказа пространства в облаке
          schema:
            type: string
      responses:
        "200":
          description: Успешное удаление заказа пространства в облаке по id заказа
          content:
            adplication/json: {}
        "default":
          description: другие ответы, кроме успешного
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error" 
    put:
      tags:
        - Clouds
      summary: редактирование заказа пространства в облаке по id заказа
      operationId: updateCloud
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cloud'
        required: true
      parameters:
        - name: CloudId
          in: path
          required: true
          description: id заказа пространства в облаке
          schema:
            type: string
      responses:
        '200':
          description: Успешное редактирование заказа пространства в облаке по id заказа
          content:
            adplication/json: {}
        "default":
          description: другие ответы, кроме успешного
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Cloud:
      type: object
      required:
        - OS
        - RAM
        - CPU
        - SSD
        - idClient
      properties:
        OS:
          type: string
          enum:
            - Windows
            - Linux
        RAM:
          type: integer
          example: 256
          description: Количество оперативной памяти
        CPU:
          type: integer
          example: 8
          description: Количество ядер процессора 
        SSD:
          type: integer
          example: 1024
          description: Количество ssd памяти
        idClient:
          type: integer
          example: 1
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - codeError
        - messageError
      properties:
        codeError:
          type: integer
          example: 123f456
          description: Код ошибки
        messageError:
          type: string
          example: error
          description: Сообщение ошибки